######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 2 10:53:54 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/grindars/sparkle/. .

QMAKE_LIBS += -lssl
QT -= gui

# Input
HEADERS += RSAKeyPair.h ArgumentsParser.h
SOURCES += main.cpp RSAKeyPair.cpp ArgumentsParser.cpp
