# #####################################################################
# Automatically generated by qmake (2.01a) ?? ???? 2 10:53:54 2009
# #####################################################################

TEMPLATE = app
TARGET = sparkle
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_LIBS += -lssl
QT -= gui
QT += network

# Input
HEADERS += RSAKeyPair.h \
    ArgumentsParser.h \
    LinkLayer.h
SOURCES += main.cpp \
    RSAKeyPair.cpp \
    ArgumentsParser.cpp \
    LinkLayer.cpp
